### PR TITLE
Add reboot system action

### PR DESCRIPTION
**Pull request by peteruithoven**
See: #119

### CODE REVIEW

**Comment by peteruithoven** [comment]
Makes total sense. 
One of the reasons for doing this PR though is check if this approach is appreciated btw.

**Comment by cassidyjames** [comment]
Since we already have "restart," I think "reboot" should just basically be an alias/keyword for that.

**Comment by peteruithoven** [comment]
Alright, one UX question is then, when searching for a alias (like "Reboot"), should it show "Restart" or "Reboot" as a result?

**Comment by danrabbit** [comment]
I believe the convention we use everywhere currently is "Restart"

**Comment by peteruithoven** [comment]
Just to be clear, you guys would prefer always showing 'Restart", also when someone searched for "reboot"? 
I think this would enable enforcing system wide terms and it would even make adding aliasses / keywords easier.

**Comment by cassidyjames** [comment]
@peteruithoven yeah I think it would be sane to make "reboot" surface the "Restart" item. Much like how searching for an app's keywords raises that app's item.

**Comment by peteruithoven** [comment]
This PR is superseded by: #144

**Pull request closed without merging**
