### PR TITLE
Improve calculator plugin

### LINKED ISSUE #439: Calculator does not show all available digits in result (shows floating point number)
## Steps to Reproduce

1. Enter 64 * 20000 in the applications menu search field

## What should happen

Should behave exactly like the calculator app whose icon it uses. i.e.,

1. Should display as 64 × 20000
2. The result should display as 1,280,000

And, if I select the result, it should open in the calculator app as it has its icon next to it.

## What actually happens

Is not consistent in behaviour with the calculator app:

1. Displays as 64 * 20000
2. Result displays in scientific notation: 1.2e+06

And, if I select the result it does not open in the calculator app.

## Platform Information

```
OS: elementary OS 5.1.7 Hera x86_64 
Host: LabTop Mk IV 
Kernel: 5.4.0-58-generic 
Uptime: 5 days, 6 hours, 55 mins 
Packages: 2047 
Shell: zsh 5.4.2 
Resolution: 1920x1080 
DE: Pantheon 
WM: Mutter(Gala) 
Terminal: io.elementary.t 
CPU: Intel i7-10710U (12) @ 4.700GHz 
GPU: Intel Device 9bca 
Memory: 4013MiB / 15883MiB 
```

### LINKED ISSUE #474: Irrelevant results with all-caps search
## What Happened

Search results are irrelevant in Wingpanel when search text is in uppercase.  (Example: **Text: 99999**)

## Expected Behavior

Search with uppercase should return same results as the ones with lowercase

## Steps to Reproduce

1. Open Applications Menu (⌘ + Space)
2. Type something in uppercase
3. Calculator ranks as the top match

https://user-images.githubusercontent.com/47198395/117439438-762f7c00-af50-11eb-9e94-c8694e75e6cf.mp4

### Logs

No Logs

## Platform Information

Operating System: elementary OS 6
Edition: (Public Beta)
Hardware Information:
- Quad-Core Intel® Core™ i5-8250U CPU @ 1.60GHz
- Intel® UHD Graphics 620 (Kabylake GT2)
- 7.7 GiB memory
- 467.2 GB storage (SSD)

Laptop Information: HP Pavilion x360

### PR DESCRIPTION
**Pull request by jeremypw**
Fixes #474 
Fixes #439

 - Accept a wider range of valid `bc` expressions, including concatenated expressions
 - Accept number base and scale expressions
 - Reject capitals if no number base expression
 - Require at least one numeric expression when not using hexadecimal
 - Show the actual result returned by `bc`, not a limited precision floating point number.

It is still rarely possible to enter strings that are not mathematical expressions that get passed to `bc` and give a spurious result but to completely prevent this while allowing a wide range of valid expressions is too complex to be worthwhile (at least not in this PR).

### CODE REVIEW

**Comment by jeremypw** [comment]
Screenshot from 2022-07-17 10 04 43
Screenshot from 2022-07-17 10 05 38
Screenshot from 2022-07-17 09 49 37
Screenshot from 2022-07-17 09 50 02
Screenshot from 2022-07-17 09 55 31

**Comment by jeremypw** [comment]
Use of variables
Screenshot from 2022-07-17 10 18 54

**Comment by tintou** [comment]
I think that we need to introduce tests to ensure that this won't regress

**Comment by jeremypw** [comment]
@tintou I did think about how to set up tests but left it until the basic concept was approved.  I do not think regressions are likely in the sense that correct single expressions that are handled correctly in main are not handled correctly here (they are still just passed to `bc`) - more likely that new types of expressions or combinations of expressions are not handled correctly.

**Comment by jeremypw** [comment]
Presumably we would need to introduce testing into master *first* in order to confirm regressions.

**Comment by jeremypw** [comment]
Essentially all this PR does is relax the filtering on expressions passed to `bc` - it does not change the expressions so it is still delegated to `bc` to either give a correct answer or an error.  Theoretically the worst that can happen is that it allows through an expression that `bc` handles incorrectly.

**Comment by jeremypw** [comment]
Testing framework now merged in.

**Comment by jeremypw** [comment]
@tintou I have now incorporated tests for the new functionality.  Are you able to review?

**Review by tintou — APPROVED** [review]

**Pull request merged**
