### PR TITLE
WIP: Use HdyPaginator for app grid

### LINKED ISSUE #128: Swipe on touch screen to switch pages
_From @alex285 on January 14, 2018 19:54_

even if i use elementary a lot, every time i open the appLauncher i'm trying to switch to next/previous page by holding down mouse and pushing on right/left

is it possible to add some gestures onWingpanel appLauncher, since it feels a natural way to navigate?

wingpanel-bug-1

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/63357724-swipe-on-touch-screen-to-switch-pages?utm_campaign=plugin&utm_content=tracker%2F62023936&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F62023936&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### LINKED ISSUE #235: Use LibHandy Paginator
Handles smooth 1:1 scrolling on x

### PR DESCRIPTION
**Pull request by Exalm**
Depends on https://github.com/elementary/os/issues/228. For testing, libhandy can just be installed manually.

Currently non-touchpad scrolling doesn't seem to work, paginator blocks it for some reason. Since scrolling over search bar or page indicators works, this looks like a paginator bug, will look into it.

Fixes #235 
Fixes #128

### CODE REVIEW

**Comment by Exalm** [comment]
Huh, looks like I only get events with `GDK_SCROLL_SMOOTH` direction in the VM. Which is pretty bad, but it would explain why non-touchpad scrolling doesn't work, so the issue is probably a non-issue.

**Comment by Exalm** [comment]
For this I think it would be good to have https://source.puri.sm/Librem5/libhandy/issues/155 fixed first.

**Comment by Exalm** [comment]
Removed mouse scrolling, paginator will handle it itself in https://source.puri.sm/Librem5/libhandy/merge_requests/327

**Comment by Exalm** [comment]
Libhandy does have mouse scrolling in master now, so that will be resolved as soon as there's 0.0.12 and it's in elementary.

Other than that, @cassidyjames mentioned dragging apps out of the menu doesn't work correctly on touch. It does work correctly for touchpad/mouse for me (dragging horizontally is dragging the app grid, dragging vertically is dragging the app), but I didn't and can't test on touchscreen.

**Comment by danrabbit** [comment]
Drag and Drop on Touchscreen doesn't work correctly in Master either, so I would consider that non-blocking and not a regression

**Comment by cassidyjames** [comment]
But dragging with a mouse is an anti-pattern IMHO; a mouse cursor is not a finger, and we typically avoid mixing mouse gestures with touch gestures. A user should be able to drag the icon in any direction with a mouse and not worry about accidentally triggering what seems like a touch gesture… is there a way to disable mouse-dragging support in the pager?

**Comment by Exalm** [comment]
It has been disabled unconditionally in libhandy now: https://source.puri.sm/Librem5/libhandy/merge_requests/331

**Comment by Exalm** [comment]
Still blocked until there's 0.0.12 and it's in elementary though.

**Comment by Exalm** [comment]
0.0.12 is released, so, should be good to go as soon as it's in elementary.

**Comment by danrabbit** [comment]
Closing because I pushed a version with conflicts resolved here: https://github.com/elementary/applications-menu/pull/360

**Pull request closed without merging**
