### PR TITLE
Send notification on uninstall success or faliure

### PR DESCRIPTION
**Pull request by arshubham**
Fixes https://github.com/elementary/applications-menu/issues/292
Requires https://github.com/elementary/appcenter/pull/1079

### CODE REVIEW

**Comment by danrabbit** [comment]
My inclination is that we wouldn’t want to handle any notifications in the applications menu.

I would think that:
* apps would disappear immediately from the applications menu as soon as I click “uninstall”.
* AppCenter would notify me if an uninstall failed, but not if it succeeds
* if an uninstall failed the app would immediately reappear in the applications menu

@cassidyjames thoughts?

**Comment by arshubham** [comment]
The appcenter returns true or false after the whole process is done. The pr handles both success and  failed cases. It waits for the status from appcenter. Let me make a small video for this. It will be more clear then.

**Comment by danrabbit** [comment]
I don't think we want the applications menu to send notifications. If notifications should be sent, they should be sent from AppCenter.

So I agree that adding a notification (or dialog) for a failed uninstall is probably good, but I think that should happen in AppCenter, not here.

I don't agree that we need a notification for a successful uninstall.

Instead, I think what we need to do is remove the AppButton from the applications menu immediately when the user requests an uninstall. If the uninstall fails, then we need to put that button back. But I think that's all the applications menu should be responsible for doing.

**Comment by arshubham** [comment]
Closing this. Will make separate pulls for UX discussed.

**Pull request closed without merging**
