### PR TITLE
Search online using the given search term

### PR DESCRIPTION
**Pull request by biswaz**
Added a plugin to search Google using the default browser. 
Solves #89

### CODE REVIEW

**Comment by cassidyjames** [comment]
This is hard coded to search using Google. I wonder if having a concept of an OS-wide search engine setting would make any sense? I spoke with @mcatanzaro and he said Epiphany could use that on elementary OS and hide its own internal search engine preferences.

**Comment by biswaz** [comment]
That sounds good to me.

**Comment by mcatanzaro** [comment]
> I spoke with @mcatanzaro and he said Epiphany could use that on elementary OS and hide its own internal search engine preferences.

Absolutely. Desktop integration is Epiphany's bread and butter. We might or might not have time to implement ourselves, but happy to take any necessary patches upstream.

**Comment by cassidyjames** [comment]
@biswaz my inclination is under Default Applications, but I understand that it's not an app and so that might be awkward. @danrabbit any thoughts?

**Comment by mattolenik** [comment]
So if you don't use Epiphany, what? You're SOL? I'm sorry I don't understand this. Why is it bad to have Google or other search engines in code or config? Is this considered "inelegant"? Users don't really give a damn about what we think is most elegant, they want search to work. This is why users tend to not take Linux desktop seriously -- the complete and mysterious lack of obvious stuff that exists _everywhere else_.

This is a non-issue, folks. The work has been completed TWICE in two independent PRs and nothing has gone anywhere.

**Comment by mattolenik** [comment]
Does that imply that search won't work if you're using something other than Epiphany? I don't understand why having Google and other search engines in code or config is so bad. Do you folks thing users give a damn about what is the most "technically elegant" solution? Or do you think they wanna press a button and do a damn web search?

**Comment by cassidyjames** [comment]
@mattolenik first, please do not come into our issue tracker to swear at us, make broad assumptions, and insult us. 

Second, no, you are incorrect.

>…an OS-wide search engine setting… Epiphany could use that on elementary OS and hide its own internal search engine preferences.

The idea being that out of the box, we wouldn't have two different places to choose a search engine (both System Settings and Epiphany), and if you chose a search engine in System Settings, the rest of the OS (including Epiphany) would follow. Searching from the Applications Menu would use the system-configured search engine and open the results in the user's default browser. Other apps could tie into this and pass search queries off to the system-wide selected search engine.

Browsers like Chrome don't care about integrating with elementary OS anyway, so searching from within Chrome will just do whatever is configured within Chrome.

**Comment by mattolenik** [comment]
And as they can, since there can be more than one search engine than Google. What I'm getting at here is, all that is good and fine, but irrelevant to users. I am puzzled because this reasoning, I thought, was the opposite of what elementary was supposed to be about.

**Comment by mcatanzaro** [comment]
Anyway the holdup here is a request to add a desktop setting rather than hardcoding Google. It really has nothing to do with Epiphany, other than that I've confirmed Epiphany would be willing to respect that setting.

**Comment by jeremypw** [comment]
If there is a desktop setting for the default the search engine (which this PR used) then someone using Chromium or another browser other than Epiphany would not be disadvantaged - provided that they set the default browser and default search engine correctly in Settings.  

The only difference I can see is that Epiphany always would honor the search engine setting whereas in theory Chromium could have a different setting internally that it would use for searches initiated in its UI but it would still use the engine set in elementary Settings when a search is initiated by Application Menu.

**Comment by mattolenik** [comment]
What exactly is wrong with hardcoding google.com? Just because we've all heard "never hardcode anything!" for years doesn't mean it's proper wisdom. Do you think users care if it's hardcoded? Why the resistance, because it might "change in the future?" Software is living stuff, we create new releases, we can keep up with changes.

You could even select default engine based on region, e.g. China can use baidu by default. There is no "elegant solution" here. There is simply stuff that should be implemented so users can be happy.

**Comment by mcatanzaro** [comment]
> What exactly is wrong with hardcoding google.com?

I don't want to use Google, I want DuckDuckGo. Pretty simple, right?

If you hardcode Google, then expect an exodus of users who don't want to use Google.

**Comment by jeremypw** [comment]
@mattolenik I would turn it round and ask "Why should there be a hard-coded engine and why should it be Google?" By hard-coding an engine we would be excluding anyone who does not use that engine which does not seem very "Linux".

**Comment by danrabbit** [comment]
Closing because this hasn't moved since July and OP seems uninterested in implementing the requested changes

**Pull request closed without merging**
