### PR TITLE
GridView.vala: Use non-clashing function name

### PR DESCRIPTION
**Pull request by jeremypw**
Fixes a compile warning.

No particular reason to use same function name as parent.

### CODE REVIEW

**Comment by davidmhewitt** [comment]
I was going to do this yesterday and then I think I found it make the keyboard navigation with the arrow keys behave incorrectly.

**Comment by jeremypw** [comment]
Hard to see why as it is a private function only called in one place as far as I can tell - but I'll investigate.

**Comment by jeremypw** [comment]
I think there is a PR from @danrabbit that tries to replace this function anyway but that does not work properly at the moment so I thought I might as well push this.

**Comment by jeremypw** [comment]
I cannot find any difference between this PR and master with regard to keyboard navigation in GridView. There is a small issue in both.

**Review by danrabbit — APPROVED** [review]
I don't see any difference between this branch and master :)

**Pull request merged**
