### PR TITLE
Sidebar: Remove broken scroll handling

### PR DESCRIPTION
**Pull request by danrabbit**
And use scroll direction constants

### CODE REVIEW

**Comment by Exalm** [comment]
Just in case, this will all have the be undone in https://github.com/elementary/applications-menu/pull/313

**Comment by danrabbit** [comment]
@Exalm Category view doesn't use a grid view anymore in master, so it shouldn't be a problem

**Comment by Exalm** [comment]
Ah, nevermind. I didn't notice this is for the category view : facepalm:

**Comment by danrabbit** [comment]
@cassidyjames thoughts on Jeremy's comment? I'm also wondering if this feature should just maybe be dropped as it seems like we don't do this anywhere else and it conflicts with scrolling in lists

**Comment by cassidyjames** [comment]
@danrabbit TIL you could scroll like that in the sidebar. It seems kinda handy/clever, but I agree it's weird with touch and would break as soon as we'd want to scroll a list. So I would be fine dropping it personally.

**Comment by danrabbit** [comment]
@cassidyjames aye aye captain!

**Comment by danrabbit** [comment]
Yeah since there's no user facing change it's probably fine

**Pull request merged**
