### PR TITLE
Build against Switchboard 3

### LINKED ISSUE #579: Update settings plugin for Switchboard-3
### What Happened?

The settings plugin currently uses switchboard-2 which is the GTK 3 version of system settings

### Steps to Reproduce

https://code.launchpad.net/~elementary-os/+archive/ubuntu/daily/+recipebuild/3624309

### Expected Behavior

Use Switchboard-3

### OS Version

Early Access

### Software Version

Compiled from git

### Log Output

_No response_

### Hardware Info

_No response_

### PR DESCRIPTION
**Pull request by danirabbit**
Fixes #579

### CODE REVIEW

**Comment by ryonakano** [comment]
Maybe we may want to update README too?

**Comment by danirabbit** [comment]
@ryonakano yes, thank you!

**Comment by tintou** [comment]
We're lucky that libswitchboard is used in another process without GTK because otherwise we would be mixing GTK3/4 which isn't allowed :slightly_smiling_face:

**Comment by danirabbit** [comment]
@tintou yeah I was worrying about that but then it seemed to work 😅

**Review by lenemter — APPROVED** [review]

**Pull request merged**
