### PR TITLE
Pin actions to the menu

### PR DESCRIPTION
**Pull request by meisenzahl**
Related to https://github.com/elementary/applications-menu/issues/398

### CODE REVIEW

**Comment by meisenzahl** [comment]
The plus icon button has no function yet. I will probably create a new view on the stack that will be displayed when the plus icon button is pressed. There you will be able to add an app action to the main page. I will probably save the selected ones as setting of `io.elementary.desktop.wingpanel.applications-menu`.

Bildschirmfoto von 2020-08-23 20-28-03

**Comment by lainsce** [comment]
This is just on me, but I think the button might need to have a symbolic variant of `list-add` due to dark theme (non-symbolic `list-add` is too dark to see there) 🤔

Other than that, try taming the height of the list. :p

**Comment by meisenzahl** [comment]
Bildschirmfoto von 2020-08-24 20-12-37

**Comment by lainsce** [comment]
A final touch for it :P

Can you make the buttons for actions have some spacing, currently they're crammed too close :P

**Comment by meisenzahl** [comment]
I would like to, but I don't know how to set the spacing for a [Gtk.ListBox](https://valadoc.org/gtk+-3.0/Gtk.ListBox.html).

**Comment by lainsce** [comment]
> I would like to, but I don't know how to set the spacing for a [Gtk.ListBox](https://valadoc.org/gtk+-3.0/Gtk.ListBox.html).

You would need to edit the `ListBox` children, the `ListBoxRow`, own `margin_bottom` to achieve the spacing needed.

**Comment by meisenzahl** [comment]
Thanks for the hint! Looks better now:

Bildschirmfoto von 2020-08-24 20-26-37

**Comment by meisenzahl** [comment]
The quick actions are now loaded from the `GLib.Settings`. Do you have an idea how the subpage for configuring the quick actions should look like?

Bildschirmfoto von 2020-08-24 20-46-08

**Comment by lainsce** [comment]
> The quick actions are now loaded from the `GLib.Settings`. Do you have an idea how the subpage for configuring the quick actions should look like?

Maybe something like this:
mockup

**Comment by meisenzahl** [comment]
Made some progress:

Bildschirmfoto von 2020-08-25 21-09-55

**Comment by meisenzahl** [comment]
The logic works now. But the layout still has enormous potential for improvement...

@lainsce So I would appreciate your help in this area :)

RecApp-2020-08-26-16_44_10

**Comment by lainsce** [comment]
You'll need to `START` align all the app names, make them semibold with H3 class, and maybe add a max-width-chars of 30 to tame the width of this sidepanel...

Also, maybe have the actions grouped in a grid inside the listboxrow instead of creating lots of listboxrows for them in the setup view.

**Comment by meisenzahl** [comment]
Many thanks for the hints! Looks already much better :)

Bildschirmfoto von 2020-08-26 20-55-25

**Comment by meisenzahl** [comment]
@lainsce maybe you could give the whole thing a finishing touch?

**Comment by lainsce** [comment]
Yeah this is the home stretch:

- Add a column_spacing of 6 to the action grid.

and it should be good to go. 🚀

**Comment by meisenzahl** [comment]
@lainsce Thanks again for the helpful feedback!

Ready for review 🤓

Bildschirmfoto von 2020-08-27 17-41-21

**Comment by martinstork** [comment]
Loving the look of this functionality. I just have a view questions.

Would it be possible to hide the Quick Actions view if it's unused?
Can this be used in the list layout?

**Comment by meisenzahl** [comment]
> Would it be possible to hide the Quick Actions view if it's unused?

In the current layout the Quick Actions and apps are side by side in the layout. Therefore it is currently not possible.

> Can this be used in the list layout?

@martinstork Can you elaborate on what you mean by this?

**Comment by martinstork** [comment]
> > Would it be possible to hide the Quick Actions view if it's unused?
> 
> In the current layout the Quick Actions and apps are side by side in the layout. Therefore it is currently not possible.

Alright. Might be possible with a toggle in the System settings as I'm seeing this as an optional feature. It would look odd when it's just empty space. 

> > Can this be used in the list layout?
> 
> @martinstork Can you elaborate on what you mean by this?

I'm not sure what it's called. I meant this category view:

Screenshot from 2020-09-19 16 46 56

**Comment by meisenzahl** [comment]
The layout for the Quick Actions is always the same. When you switch to category view, it looks like this:

Bildschirmfoto von 2020-09-19 17-21-14

**Comment by fabiozaramella** [comment]
> The layout for the Quick Actions is always the same. When you switch to category view, it looks like this:
> 
> Bildschirmfoto von 2020-09-19 17-21-14

I'm sorry but I really can't get used to it... is simply ugly to have to sidebar next to each other. 😅 What about adding a third modebutton for a separate "Quick actions view" and show the list of available quick actions per-app, as well as the ability to add new ones, there? @elementary/ux

**Comment by cassidyjames** [comment]
Hrm, I really don't think I'm a fan of this direction. I think this needs more thought design-wise before we get farther here.

**Comment by Loreno10** [comment]
It looks a bit "heavy" to me. I like the minimalistic look fo the applicaitons menu. I think the quick actions could appear for specific apps when they are middle-clicked, or something like that?

**Comment by cassidyjames** [comment]
@Loreno10 quick actions show when right-clicked. :stuck_out_tongue_closed_eyes:

**Comment by Loreno10** [comment]
> @Loreno10 quick actions show when right-clicked. 😝

Great job then ;)

**Pull request closed without merging**
