### PR TITLE
SlingshotView: Fix moving down from searchbar in category view

### PR DESCRIPTION
**Pull request by danrabbit**
Shift shortcuts don't seem to work in master either, so moving this code is theoretical I guess. This branch doesn't solve that issue.

### CODE REVIEW

**Comment by jeremypw** [comment]
If this is intended to fix #194 then it does not seem to work.  I can still lock out subsequent key presses by entering one character and immediately pressing the down arrow. Some kind of race I guess.

**Comment by jeremypw** [comment]
Not sure we need three separate but interconnected key press handlers :-(

**Comment by danrabbit** [comment]
No this isn't a fix for #194 

In master, pressing down never moves focus into the category view. Instead of just passing focus down and letting the view do its thing, it's trying to manually capture arrow events and then tell the view to do things. It's just way over-engineered and crappy.

My ultimate goal is that the views contain shortcuts that are specific to keyboard focus being in that view. Right now there's just a ton of broken shortcuts and events are getting swallowed by views that don't have focus and it's complicated. I agree that having the search entry connected to two handlers seems bonkers. I'm trying to simplify things where I can. It's a mess :(

**Comment by jeremypw** [comment]
OK, I'll review on that basis.

**Pull request merged**
